spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    org:
      hibernate:
        envers:
          audit_table_suffix: _history
