server:
  port: 8082
spring:
  application:
    name: cafe
  profiles:
    active: default
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      label: master