server:
  port: 8081
spring:
  application:
    name: user

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

cafe:
  url: http://localhost:8082

